---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  interval: 2m
  ref:
    branch: ${branch:-main}
  url: https://github.com/buttahtoast/flux
  #verify:
  #  mode: head
  #  secretRef:
  #    name: admin-gpg-pub-keys   