---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
spec:
  interval: 5m
  chart:
    spec:
      chart: "metallb"
      version: "{{ .Values.apps.metallb.version }}"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: "{{ .Release.Namespace }}"
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    existingConfigMap: "bgp-config"