apiVersion: v2
name: infra
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
- name: helmize
  # Make sure to use a fixed version
  version: "0.1.0-rc.5"
  #repository: "https://buttahtoast.github.io/helm-charts/"
  repository: "file://helmize/charts/helmize"
