apiVersion: v2
name: infra
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
- name: helmize
  version: "0.1.0-rc.6"
  repository: "https://oliverbaehler.github.io/helmize/"
