---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cf-buttahtoast
spec:
  interval: 5m
  dependsOn:
  - name: cert-manager
    namespace: "{{ .Release.Namespace }}"
  chart:
    spec:
      chart: "raw"
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: "bedag"
        namespace: "{{ .Release.Namespace }}"
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    resources:
    - apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: cf-buttahtoast
      spec:
        acme:
          email: {{ .Values.infra.cert.email }}
          server: https://acme-v02.api.letsencrypt.org/directory
          privateKeySecretRef:
            name: example-issuer-account-key
          solvers:
          - dns01:
              cloudflare:
                email: {{ .Values.infra.cert.email }}
                apiTokenSecretRef:
                  name: cloudflare-api-token-secret
                  key: api-token
            selector:
              dnsZones:
              - "buttahtoast.ch"
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cloudflare-api-token-secret
      type: Opaque
      stringData: 
        api-token: {{ .Values.secrets.cloudflare_token }}
