apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- repository.yaml
- token.yaml
secretGenerator:
- name: admin-gpg-pub-keys
  namespace: flux-system
  files:
  - ../../../gpg/olb.asc
  - ../../../gpg/kkl.asc
  type: Opaque
generatorOptions:
 disableNameSuffixHash: true
