{{- if $.Values.apps.certManager }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: "{{ .namespace }}"
spec:
  interval: 5m
  chart:
    spec:
      chart: "cert-manager"
      version: "{{ .version }}"
      sourceRef:
        kind: HelmRepository
        name: "jetstack"
        namespace: "{{ .namespace }}"
  upgrade:
    remediation:
      remediateLastFailure: true
  values: 
    installCRDs: true
{{- end }}