---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mailu
  namespace: kevin
spec:
  interval: 5m
  chart:
    spec:
      chart: "mailu"
      version: "0.3.1"
      sourceRef:
        kind: HelmRepository
        name: "mailu"
        namespace: "kevin"
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    domain: sudo-i.net
    initialAccount:
      domain: sudo-i.net
      username: admin
      password: admin
    persistence:
      size: 10Gi
    hostnames:
    - mx3.sudo-i.net
    secretKey: chang3m3!