apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- gotk-components.yaml
- gotk-sync.yaml
patches:
- path: values.yaml
  target:
    kind: HelmRelease
    name: infrastructure
