{{- if $.Values.apps.externalDns.enabled -}}
---
helmize:
  id: "external-dns-release"
  render: false
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns-cf-buttahtoast
spec:
  interval: 5m
  chart:
    spec:
      chart: "external-dns"
      version: "{{ .Values.apps.externalDns.version }}"
      sourceRef:
        kind: HelmRepository
        name: "external-dns"
        namespace: "{{ .Release.Namespace }}"
  upgrade:
    remediation:
      remediateLastFailure: true
---


{{- end -}}