apiVersion: v1
kind: ConfigMap
metadata:
  name: bgp-config
data:
  config: |
    peers:
      - peer-address: 10.124.1.1
        peer-asn: 65542
        my-asn: 64512
    address-pools:
      - name: intern
        protocol: bgp
        addresses:
          - "10.124.{{ .Values.cluster.id }}.0/24"