apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rancher-intern
  namespace: cattle-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "cf-buttahtoast"
    enable-owasp-modsecurity-crs: "true"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
spec:
  tls:
  - hosts:
    - "{{ .Values.cluster.id }}.harv.buttahtoast.ch"
    secretName: podinfo
  ingressClassName: intern
  rules:
  - host: "{{ .Values.cluster.id }}.harv.buttahtoast.ch"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rancher
            port:
              number: 80