---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 1m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./infra/
      version: ">0.0.0-0"
      sourceRef:
        name: flux-system 
        kind: GitRepository
  #valuesFrom:
  #  - kind: Secret
  #    name: harbor-external-secrets
  values:

    ## Global Configuration
    namespace: "buttah-system"
    
    ## Application Configuration
    apps:
      metallb:
        version: "0.12.1"
    
      ingress:
        version: "4.0.19"
    
      certManager:
        version: "1.8.0"
    
      externalDns:
        version: "1.7.1"



